[[headers]]
  for = "/"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      connect-src 'self' https://*.supabase.co https://www.google.com https://www.gstatic.com;
      script-src 'self' https://www.google.com https://www.gstatic.com;
      style-src 'self' 'unsafe-inline';
      frame-src https://www.google.com;
    """
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
