name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy functions to Supabase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          path: repo

      - name: Download Supabase CLI binary
        run: |
          curl -L https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz -o supabase.tar.gz
          tar -xzf supabase.tar.gz
          chmod +x supabase
          sudo mv supabase /usr/local/bin

      - name: Link Supabase project
        working-directory: ./repo
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref ajxymcztnprndgiupimi

      - name: Deploy validate-captcha function
        working-directory: ./repo
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
        run: |
          supabase functions deploy validate-captcha

      - name: Deploy rate-limit-login function
        working-directory: ./repo
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase functions deploy rate-limit-login
