name: Deploy Supabase Edge Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy function to Supabase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Download Supabase CLI
        run: |
          curl -L https://github.com/supabase/cli/releases/download/v1.163.1/supabase_1.163.1_linux_amd64.tar.gz | tar -xz
          sudo mv supabase /usr/local/bin

      - name: Deploy validate-captcha function
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
        run: |
          supabase link --project-ref ajxymcztnprndgiupimi
          supabase functions deploy validate-captcha
